name: Docker Quotes Images

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image in respective Directories
      run: |
        cd quote_disp
        docker build . --file Dockerfile --tag dis:$(date +%s)
        cd ..
        cd quote_gen
        docker build . --file Dockerfile --tag gen:$(date +%s)
    - name: Create Docker Network
      run:  docker network create quote-network
    - name: Create Docker Container with repective images & network
      run:  | 
        docker run -d --name gen -p 5000:5000 --network quote-network gen
        docker run -d --name disp -p 5001:5001 --link gen:gen --network quote-network dis
